# Generated by Django 4.2.1 on 2023-08-28 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=50)),
                ('empDepart', models.CharField(max_length=100, null=True)),
                ('empDesignation', models.CharField(max_length=100, null=True)),
                ('empGender', models.CharField(max_length=10, null=True)),
                ('empContactNo', models.CharField(max_length=10, null=True)),
                ('empJoiningdate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
