# Generated by Django 4.2.1 on 2023-08-28 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyOneName', models.CharField(max_length=100, null=True)),
                ('ComanyOneDesig', models.CharField(max_length=100, null=True)),
                ('ComanyOneSalary', models.CharField(max_length=100, null=True)),
                ('CompanyOneDuration', models.CharField(max_length=100, null=True)),
                ('CompanyTwoName', models.CharField(max_length=100, null=True)),
                ('ComanyTwoDesig', models.CharField(max_length=100, null=True)),
                ('ComanyTwoSalary', models.CharField(max_length=100, null=True)),
                ('CompanyTwoDuration', models.CharField(max_length=100, null=True)),
                ('CompanyThreeName', models.CharField(max_length=100, null=True)),
                ('ComanyThreeDesig', models.CharField(max_length=100, null=True)),
                ('ComanyThreeSalary', models.CharField(max_length=100, null=True)),
                ('CompanyThreeDuration', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorseMaster', models.CharField(max_length=100, null=True)),
                ('schoolMaster', models.CharField(max_length=100, null=True)),
                ('yearOfPassMaster', models.CharField(max_length=100, null=True)),
                ('precentageMaster', models.CharField(max_length=100, null=True)),
                ('CorseBachlor', models.CharField(max_length=100, null=True)),
                ('schoolBachlor', models.CharField(max_length=100, null=True)),
                ('yearOfPassBachlor', models.DateField(max_length=100, null=True)),
                ('precentageBachlor', models.CharField(max_length=100, null=True)),
                ('CorsePlus2', models.CharField(max_length=100, null=True)),
                ('schoolPlus2', models.CharField(max_length=100, null=True)),
                ('yearOfPassPlus2', models.DateField(max_length=100, null=True)),
                ('precentagePlus2', models.CharField(max_length=100, null=True)),
                ('CorseSEE', models.CharField(max_length=100, null=True)),
                ('schoolSEE', models.CharField(max_length=100, null=True)),
                ('yearOfPassSEE', models.DateField(max_length=100, null=True)),
                ('precentageSEE', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
