# Generated by Django 4.2.1 on 2023-09-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeexp_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexp',
            old_name='ComanyOneDesig',
            new_name='CompanyOneDesig',
        ),
        migrations.RenameField(
            model_name='employeeexp',
            old_name='ComanyOneSalary',
            new_name='CompanyOneSalary',
        ),
        migrations.RenameField(
            model_name='employeeexp',
            old_name='ComanyThreeDesig',
            new_name='CompanyThreeDesig',
        ),
        migrations.RenameField(
            model_name='employeeexp',
            old_name='ComanyThreeSalary',
            new_name='CompanyThreeSalary',
        ),
        migrations.RenameField(
            model_name='employeeexp',
            old_name='ComanyTwoDesig',
            new_name='CompanyTwoDesig',
        ),
        migrations.RenameField(
            model_name='employeeexp',
            old_name='ComanyTwoSalary',
            new_name='CompanyTwoSalary',
        ),
    ]
